### PR TITLE
Allow empty soap actions

### PR DESCRIPTION
**Pull request by danbaranov**
This helps working with Google WSDLs

Also closes https://github.com/elixir-soap/soap/issues/67 and https://github.com/elixir-soap/soap/issues/69

### CODE REVIEW

**Comment by Nitrino** [comment]
@danbaranov amazing work 🔥
Could you add tests for these cases and checking their WSDL?

**Comment by danbaranov** [comment]
Hey @Nitrino. I'll do that in 2-3 weeks when I got a bit of time

**Comment by nik-cars** [comment]
In order to fix #69 I needed to also apply one of the fixes to the protocol schema function
```elixir
def get_protocol_namespace(wsdl) do
    case Application.fetch_env!(:soap, :globals)[:absent_schema_namespace] do
      true ->
        []
        _ ->
    wsdl
    |> xpath(~x"//namespace::*"l)
    |> Enum.find(fn {_, _, _, _, url} -> url == :"http://schemas.xmlsoap.org/wsdl/" end)
    |> elem(3)
        end
  end
```

**Comment by churcho** [comment]
Any chance we can get traction on these issues?

**Comment by ryanw** [comment]
Any plans to merge this fix? It's been here for 2 years.

**Comment by rubysolo** [comment]
I think this is a duplicate of #85, which was merged.

**Comment by Nitrino** [comment]
@rubysolo Thanks. Yes, it was done in #85.

**Comment by fram-sse** [comment]
Looks like the fix for the :absent_schema_namespace was never applied to the codebase

**Pull request closed without merging**
