### PR TITLE
Misc doc changes

### PR DESCRIPTION
**Pull request by kianmeng**
Besides other documentation changes, this commit ensures the generated
HTML doc for HexDocs.pm will become the source of truth for this Elixir
library and leverage on latest features of ExDoc.

### CODE REVIEW

**Comment by kianmeng** [comment]
@Nitrino Should I resolve the conflict and resubmit the PR again?

**Comment by Nitrino** [comment]
@kianmeng Yes, please

**Comment by kianmeng** [comment]
@Nitrino Done. Please check.

**Comment by Nitrino** [comment]
@kianmeng Thanks

**Comment by kianmeng** [comment]
:+1: :tada:

**Pull request merged**
